import { it } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, writeFileSync, mkdtempSync, rmSync, mkdirSync, cpSync, symlinkSync, statSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { AVVISNINGSFILER, avvisningsforslagshash, avvisningspakethash, forberedAvvisningspaket, verkstallAvvisningspaket, type Avvisningspaket } from "../src/avvisningspaket.ts";
import { lasFillage } from "../src/datatransaktion.ts";
import { reviewId, type ReviewCandidate } from "../src/review.ts";
const ko: ReviewCandidate[] = JSON.parse(readFileSync(new URL("../../data/needs_review.json", import.meta.url), "utf8")); assert.ok(ko.length > 0);
const fore = { "needs_review.json": JSON.stringify(ko), "avvisade.json": "[]" }, rad = { id: reviewId(ko[0]!), skal: "Kandidaten är prövad som testfall och ska inte publiceras i detta isolerade prov." };
function besluta(p: Avvisningspaket): Avvisningspaket { const c = structuredClone(p); c.beslut = { bedomare: "syntetiskt-testkonto", utfall: "avvisa", motivering: "Tekniskt prov av avslagskontraktet.", forslagshash: avvisningsforslagshash(c), kalla: { system: "github", association: "OWNER", handelse: "https://github.com/test/repo/issues/1#issuecomment-1" } }; return c; }
it("verklig CLI kräver privat paket och separat beslut", () => { const root = mkdtempSync(join(tmpdir(), "avvisningscli-")), d = join(root, "data"), pipe = join(root, "pipeline"); try { mkdirSync(d); mkdirSync(join(pipe, "scripts"), { recursive: true }); for (const n of ["src", "schemas", "prompts"]) cpSync(join(import.meta.dirname, "..", n), join(pipe, n), { recursive: true }); cpSync(join(import.meta.dirname, "../package.json"), join(pipe, "package.json")); cpSync(join(import.meta.dirname, "../scripts/avvisa-lista.mts"), join(pipe, "scripts/avvisa-lista.mts")); symlinkSync(join(import.meta.dirname, "../node_modules"), join(pipe, "node_modules"), "dir"); for (const [n, s] of Object.entries(fore)) writeFileSync(join(d, n), s); const input = join(root, "rader.json"), output = join(root, "paket.json"); writeFileSync(input, JSON.stringify([rad])); const run = (...a: string[]) => spawnSync(process.execPath, ["--import", "tsx/esm", "scripts/avvisa-lista.mts", ...a], { cwd: pipe, encoding: "utf8" }); let r = run("forbered", input, output); assert.equal(r.status, 0, r.stderr); assert.equal(statSync(output).mode & 0o777, 0o600); assert.notEqual(run(input, "--skriv").status, 0); assert.notEqual(run("kontroll", output).status, 0); const p = besluta(JSON.parse(readFileSync(output, "utf8")) as Avvisningspaket); writeFileSync(output, JSON.stringify(p)); r = run("kontroll", output); assert.equal(r.status, 0, r.stderr); assert.notEqual(run("verkstall", output, avvisningspakethash(p)).status, 0); r = run("verkstall", output, avvisningspakethash(p), "--skriv"); assert.equal(r.status, 0, r.stderr); assert.deepEqual(lasFillage(d, AVVISNINGSFILER), p.filer.efter); } finally { rmSync(root, { recursive: true, force: true }); } });
it("binder exakt kandidat, skäl, separat beslut och båda efterfilerna", () => { const d = mkdtempSync(join(tmpdir(), "avvisning-")); try { for (const [n, s] of Object.entries(fore)) writeFileSync(join(d, n), s); const u = forberedAvvisningspaket([rad], fore, new Date("2026-09-14T14:00:00Z")); assert.throws(() => verkstallAvvisningspaket(d, u, avvisningspakethash(u)), /mänskligt avslagsbeslut/u); const p = besluta(u), h = avvisningspakethash(p); assert.throws(() => verkstallAvvisningspaket(d, p, "0".repeat(64)), /hela paketet/u); const bytt = structuredClone(p); bytt.rader[0]!.skal += " ändrat"; assert.throws(() => verkstallAvvisningspaket(d, bytt, avvisningspakethash(bytt)), /slutform/u); assert.deepEqual(lasFillage(d, AVVISNINGSFILER), fore); verkstallAvvisningspaket(d, p, h); assert.deepEqual(lasFillage(d, AVVISNINGSFILER), p.filer.efter); assert.throws(() => verkstallAvvisningspaket(d, p, h), /föreläge/u); } finally { rmSync(d, { recursive: true, force: true }); } });
it("avvisar korta skäl, okända radfält och dubblerade köidentiteter", () => { assert.throws(() => forberedAvvisningspaket([{ id: rad.id, skal: "kort" }], fore, new Date()), /motiverad/u); assert.throws(() => forberedAvvisningspaket([{ ...rad, extra: true } as never], fore, new Date()), /motiverad/u); assert.throws(() => forberedAvvisningspaket([rad], { ...fore, "needs_review.json": JSON.stringify([ko[0], ko[0]]) }, new Date()), /Dubblerad kandidatidentitet/u); });
