import { it } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { kanoniskJson } from "../src/underlagsversion.ts";
import { tillampaProvatKalkylbeslut } from "../src/kalkylbeslut.ts";
import { provatKalkylunderlag } from "./fixtures/provat-kalkylunderlag.ts";
import { reviewId, type ReviewCandidate } from "../src/review.ts";
import type { PromiseEntry } from "../src/loftesforslag.ts";
const loften: PromiseEntry[] = JSON.parse(readFileSync(new URL("../../data/promises.json", import.meta.url), "utf8"));
const ko: ReviewCandidate[] = JSON.parse(readFileSync(new URL("../../data/needs_review.json", import.meta.url), "utf8"));
const k = ko.find((p) => p.candidate?.quote && !p.candidate.person && p.cost?.calculation && p.cost.calculation.length <= 800)!;
const m = loften.find((p) => p.status === "aktiv" && p.loftestyp === "reform" && !p.person && JSON.stringify([...p.parties].sort()) === JSON.stringify([...(k.candidate.parties ?? [])].sort()))!;
const rad = { fran: reviewId(k), till: m.id, kostnad: { ...k.cost! }, skal: "Tekniskt prov; period och kostnadstyp följer den nya kalkylen." };
it("kalkylbeslut kräver underlag, exakt beslut och färdig prövning", () => {
  const u = provatKalkylunderlag(rad, loften, k), fore = JSON.stringify(loften);
  assert.throws(() => tillampaProvatKalkylbeslut(rad, loften, k, undefined, undefined), /kräver/u);
  assert.throws(() => tillampaProvatKalkylbeslut(rad, loften, k, u, undefined), /kräver/u);
  assert.throws(() => tillampaProvatKalkylbeslut(rad, loften, k, u, "0".repeat(64)), /referens/u);
  const andrat = structuredClone(u); andrat.provning.bedomningar[0]!.utfall = "oavgjort";
  andrat.provningshash = createHash("sha256").update(kanoniskJson(andrat.provning)).digest("hex");
  assert.throws(() => tillampaProvatKalkylbeslut(rad, loften, k, andrat, u.provningshash), /referens/u);
  assert.throws(() => tillampaProvatKalkylbeslut(rad, loften, k, andrat, andrat.provningshash), /inte klar/u);
  assert.throws(() => tillampaProvatKalkylbeslut({ ...rad, skal: "Ändrat skäl" }, loften, k, u, u.provningshash), /argument/u);
  const refs = structuredClone(u); refs.aktuellaReferenser[0]!.innehall += " ändrat";
  assert.throws(() => tillampaProvatKalkylbeslut(rad, loften, k, refs, refs.provningshash), /inte klar/u);
  const efter = tillampaProvatKalkylbeslut(rad, loften, k, u, u.provningshash);
  assert.deepEqual(efter.find((p) => p.id === m.id), u.forslag.nyttLofte);
  assert.equal(JSON.stringify(loften), fore);
});
