import { it } from "node:test";
import assert from "node:assert/strict";
import { readFileSync, writeFileSync, mkdtempSync, rmSync, mkdirSync, cpSync, symlinkSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { NOLLFILER, forberedNollpaket, nollpakethash, verkstallNollpaket, type Nollindata, type Nollpaket } from "../src/nollpaket.ts";
import { lasFillage } from "../src/datatransaktion.ts";
import type { PromiseEntry } from "../src/loftesforslag.ts";
const verkliga: PromiseEntry[] = JSON.parse(readFileSync(new URL("../../data/promises.json", import.meta.url), "utf8"));
const mal = structuredClone(verkliga.find((p) => p.status === "aktiv")!); mal.id = "p-2026-9004"; mal.group_id = null; mal.quote = "Vi ska utreda frågan och återkomma med en plan."; mal.cost = { ...mal.cost, type: "utgift", period: "per_ar", msek_low: 10, msek_base: 20, msek_high: 30, calculation: "Felaktigt pris." };
const fore = { "promises.json": JSON.stringify([mal]), "rattelser.json": "[]", "changelog.json": "[]" };
const indata: Nollindata = { rader: [{ id: mal.id, regel: "utredning", utrakning: "Löftet gäller en utredning och prissätts till noll; eventuell senare politik ingår inte.", skal: "Citatet lovar bara en utredning och ingen efterföljande åtgärd." }], material: { [mal.id]: [{ id: "kalla", slag: "kalla", adress: "test:kalla", innehall: "Syntetiskt material." }, { id: "regel", slag: "regel", adress: "test:regel", innehall: "Tekniskt formatprov." }] }, varfor: "Tekniskt prov i isolerad kopia.", orsak: "annat" };
function klar(p: Nollpaket): Nollpaket { const c = structuredClone(p); for (const x of c.provningar) { x.bedomare = "Syntetiskt formatprov, ingen mänsklig attest"; for (const b of x.bedomningar) { b.utfall = "styrkt"; b.motivering = "Tekniskt kontraktsprov, inte sakbedömning."; b.belagg = ["kalla", "regel"]; } } return c; }
it("verklig CLI avvisar den gamla direktvägen och kräver komplett beslut", () => { const root = mkdtempSync(join(tmpdir(), "nollcli-")), d = join(root, "data"), pipe = join(root, "pipeline"); try { mkdirSync(d); cpSync(join(import.meta.dirname, "../../data/parties.json"), join(d, "parties.json")); mkdirSync(join(pipe, "scripts"), { recursive: true }); for (const n of ["src", "schemas", "prompts"]) cpSync(join(import.meta.dirname, "..", n), join(pipe, n), { recursive: true }); cpSync(join(import.meta.dirname, "../package.json"), join(pipe, "package.json")); cpSync(join(import.meta.dirname, "../scripts/regelnollning.mts"), join(pipe, "scripts/regelnollning.mts")); symlinkSync(join(import.meta.dirname, "../node_modules"), join(pipe, "node_modules"), "dir"); for (const [n, s] of Object.entries(fore)) writeFileSync(join(d, n), s); const input = join(root, "indata.json"), output = join(root, "paket.json"); writeFileSync(input, JSON.stringify(indata)); const run = (...a: string[]) => spawnSync(process.execPath, ["--import", "tsx/esm", "scripts/regelnollning.mts", ...a], { cwd: pipe, encoding: "utf8" }); let r = run("forbered", input, output); assert.equal(r.status, 0, r.stderr); assert.notEqual(run(input, "--skriv", "--varfor", "test").status, 0); assert.notEqual(run("kontroll", output).status, 0); const p = klar(JSON.parse(readFileSync(output, "utf8")) as Nollpaket); writeFileSync(output, JSON.stringify(p)); r = run("kontroll", output); assert.equal(r.status, 0, r.stderr); assert.notEqual(run("verkstall", output, nollpakethash(p)).status, 0); r = run("verkstall", output, nollpakethash(p), "--skriv"); assert.equal(r.status, 0, r.stderr); assert.deepEqual(lasFillage(d, NOLLFILER), p.filer.efter); } finally { rmSync(root, { recursive: true, force: true }); } });
it("kräver komplett prövat nollpaket och extern beslutshash", () => { const d = mkdtempSync(join(tmpdir(), "nollpaket-")); try { for (const [n, s] of Object.entries(fore)) writeFileSync(join(d, n), s); const u = forberedNollpaket(indata, fore, new Date("2026-09-14T13:00:00Z")); assert.throws(() => verkstallNollpaket(d, u, nollpakethash(u)), /inte klar/u); const p = klar(u), h = nollpakethash(p); assert.throws(() => verkstallNollpaket(d, p, "0".repeat(64)), /hela paketet/u); const bytt = structuredClone(p); bytt.filer.efter["changelog.json"] = "[]"; assert.throws(() => verkstallNollpaket(d, bytt, nollpakethash(bytt)), /slutform/u); assert.deepEqual(lasFillage(d, NOLLFILER), fore); verkstallNollpaket(d, p, h); assert.deepEqual(lasFillage(d, NOLLFILER), p.filer.efter); assert.throws(() => verkstallNollpaket(d, p, h), /föreläge/u); } finally { rmSync(d, { recursive: true, force: true }); } });
