/**
 * FÄLLS AV: att sluta känna igen en av sidfotens former, att städa bort
 * brödtext, eller att lämna en tom beskrivning efter sig.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { utanSidfot } from "../src/prtexten.ts";

const KROPP = "Rättar en trasig grind.\n\n## Kontroll\n\nSviten grön.";

test("formen verktyget lägger på tas bort", () => {
  const med = `${KROPP}\n\n---\n_Generated by [Claude Code](https://claude.ai/code/session_016F6V)_`;
  const ut = utanSidfot(med);
  assert.equal(ut.stadad, true);
  assert.equal(ut.text, KROPP + "\n");
});

test("formen sessionen brukade skriva tas bort, med sessionslänken", () => {
  const med = `${KROPP}\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\n\nhttps://claude.ai/code/session_016F6V`;
  const ut = utanSidfot(med);
  assert.equal(ut.stadad, true);
  assert.equal(ut.text, KROPP + "\n");
});

test("samma form två gånger städas i ett svep", () => {
  // En PR som redigerats och öppnats om kan ha fått sidfoten staplad.
  const med = `${KROPP}\n\n---\n_Generated by [Claude Code](https://x)_\n\n---\n_Generated by [Claude Code](https://x)_`;
  assert.equal(utanSidfot(med).text, KROPP + "\n");
});

test("en ren beskrivning lämnas orörd", () => {
  const ut = utanSidfot(KROPP);
  assert.equal(ut.stadad, false);
  assert.equal(ut.text, KROPP + "\n");
});

test("brödtext som nämner verktyget rörs inte", () => {
  // Regeln gäller sidfoten, inte varje omnämnande. En mening mitt i texten är
  // något en människa ska titta på — att redigera bort den i tysthet vore att
  // skriva om vad någon sagt.
  const mitt = `Inledning.\n\n_Generated by [Claude Code](https://x)_ står i mallen.\n\nAvslutning.`;
  const ut = utanSidfot(mitt);
  assert.equal(ut.stadad, false, "en träff mitt i texten är inte en sidfot");
});

test("en beskrivning som bara är en sidfot lämnas som den är", () => {
  // Tom beskrivning är inte en förbättring: då säger PR:en ingenting alls.
  const bara = "---\n_Generated by [Claude Code](https://x)_";
  const ut = utanSidfot(bara);
  assert.equal(ut.stadad, false);
  assert.equal(ut.text, bara);
});

test("en tom beskrivning kraschar inte", () => {
  assert.equal(utanSidfot("").stadad, false);
});
