import { it } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { forberedRubrikforslag, tillampaRubrikforslag } from "../src/rubrikforslag.ts";
import { byggRubrikunderlag, skapaSakprovning, sakprovningsBeredskap } from "../src/sakprovning.ts";
import type { PromiseEntry } from "../src/loftesforslag.ts";
const loften: PromiseEntry[] = JSON.parse(readFileSync(new URL("../../data/promises.json", import.meta.url), "utf8"));
const mal = loften.find(p => p.status === "aktiv" && p.quote.length > 60 && p.title !== p.quote.slice(0, 60).split(" ").slice(0, -1).join(" "))!;
assert.ok(mal);
const rad = { id: mal.id, rubrik: mal.quote.slice(0, 60).split(" ").slice(0, -1).join(" "), skal: "Syntetiskt kontraktsprov, inte en sakbedömning." };
const nu = new Date("2026-09-20T00:00:00Z");
it("fryser enbart rubrik och historik och lämnar original samt sakprövning orörda", () => {
  const fore = JSON.stringify(loften);
  const f = forberedRubrikforslag(rad, loften, nu);
  assert.deepEqual({ ...f.nyttLofte, title: mal.title, history: mal.history }, mal);
  assert.equal(f.nyttLofte.title, rad.rubrik);
  assert.equal(f.nyttLofte.history.length, mal.history.length + 1);
  assert.deepEqual(tillampaRubrikforslag(f, loften, f.hash).find(p => p.id === mal.id), f.nyttLofte);
  const u = byggRubrikunderlag(f, loften, []), prov = skapaSakprovning(u);
  assert.ok(prov.bedomningar.every(b => b.utfall === "oavgjort"));
  assert.equal(sakprovningsBeredskap(prov, u).klar, false);
  assert.equal(JSON.stringify(loften), fore);
});
it("tomt bestånd, okänt mål, ändrat föreläge, manipulerad slutform och fel hash stoppas", () => {
  assert.throws(() => forberedRubrikforslag(rad, [], nu));
  assert.throws(() => forberedRubrikforslag({ ...rad, id: "saknas" }, loften, nu));
  const f = forberedRubrikforslag(rad, loften, nu);
  assert.throws(() => tillampaRubrikforslag(f, loften, "0".repeat(64)));
  const andra = structuredClone(loften); andra[0]!.quote += " ändrad";
  assert.throws(() => tillampaRubrikforslag(f, andra, f.hash));
  f.nyttLofte.parties = ["annat"];
  assert.throws(() => tillampaRubrikforslag(f, loften, f.hash));
});
