/**
 * Sidfoten i en PR-beskrivning — regeln, som en ren funktion.
 *
 * PR-texten är projektets ansikte utåt: repot är publikt och beskrivningen
 * läses av folk som inte var med. Raden «genererad med» plus en sessionslänk
 * säger vilket verktyg som kört, inte vad ändringen gör, och vem som skrev
 * något är ingen uppgift om det som skrevs.
 *
 * **Varför det behöver vara en grind och inte en regel i text.** Sidfoten
 * skrivs inte av den som skriver PR-texten. Den läggs på serversidan när
 * PR:en skapas — efter att texten lämnat sessionen — så varken en skriven
 * regel eller `attribution.pr` i `.claude/settings.json` når den. Båda
 * behövs ändå: inställningen tar bort raden ur det som skrivs, den här
 * grinden tar bort det som läggs till efteråt.
 *
 * Mätt 2026-09-02: reglerna skrevs, och samma dygn bar två PR:er sidfoten —
 * en av dem den som införde inställningen mot den.
 *
 * Städningen är avsiktligt snäv. Den tar bort en sidfot som står **sist** och
 * matchar en känd form; den skriver aldrig om brödtext. En rad mitt i texten
 * som råkar nämna verktyget är något en människa ska titta på, inte något ett
 * arbetsflöde ska redigera bort i tysthet.
 */

/**
 * Kända former på sidfoten.
 *
 * Två i dag: den sessionen brukade skriva själv, och den GitHub-verktyget
 * lägger på. Båda kan föregås av en vågrät linje och omges av tomrader.
 * Mönstren är ankrade i slutet — därav `$` och `\s*` — så att bara en
 * verklig sidfot träffas.
 */
const SIDFOTEN: readonly RegExp[] = [
  // 🤖 Generated with [Claude Code](https://claude.com/claude-code)
  // följt av en valfri sessionslänk på egen rad.
  /\n*(?:^|\n)\s*(?:---\s*\n)?\s*🤖\s*Generated with \[Claude Code\]\([^)]*\)\s*(?:\n+https?:\/\/\S+)?\s*$/u,
  // ---
  // _Generated by [Claude Code](https://claude.ai/code/session_…)_
  /\n*(?:^|\n)\s*(?:---\s*\n)?\s*_Generated by \[Claude Code\]\([^)]*\)_\s*$/u,
];

/**
 * Beskrivningen utan sidfot, och om något togs bort.
 *
 * Flera sidfötter kan ha hunnit staplas på varandra — en PR som redigerats
 * och öppnats om — så städningen görs tills ingen form längre träffar.
 */
export function utanSidfot(kropp: string): { text: string; stadad: boolean } {
  let text = kropp;
  let stadad = false;
  for (let varv = 0; varv < 10; varv++) {
    const fore = text;
    for (const m of SIDFOTEN) text = text.replace(m, "");
    if (text === fore) break;
    stadad = true;
  }
  // En beskrivning som BARA var en sidfot blir tom, och en tom beskrivning är
  // inte en förbättring — då säger PR:en ingenting alls. Rör den inte.
  if (stadad && text.trim() === "") return { text: kropp, stadad: false };
  return { text: text.trimEnd() + "\n", stadad };
}
